// POLL ACTIONS
export const GET_ALL_POLLS_STARTED = "GET_ALL_POLLS_STARTED";
export const GET_ALL_POLLS_SUCCESS = "GET_ALL_POLLS_SUCCESS";
export const GET_ALL_POLLS_FAILED = "GET_ALL_POLLS_FAILED";

// QUESTION ACTIONS
export const GET_ALL_QUESTIONS_STARTED = "GET_ALL_QUESTIONS_STARTED";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS";
export const GET_ALL_QUESTIONS_FAILED = "GET_ALL_QUESTIONS_FAILED";

// ANSWER ACTIONS
export const SET_ANSWER = "SET_ANSWER";
export const SEND_POLL_ANSWERS_STARTED = "SEND_POLL_ANSWERS_STARTED";
export const SEND_POLL_ANSWERS_SUCCESS = "SEND_POLL_ANSWERS_SUCCESS";
export const SEND_POLL_ANSWERS_FAILED = "SEND_POLL_ANSWERS_FAILED";