// POLL ACTIONS
export const GET_ALL_POLLS_STARTED = "GET_ALL_POLLS_STARTED";
export const GET_ALL_POLLS_SUCCESS = "GET_ALL_POLLS_SUCCESS";
export const GET_ALL_POLLS_FAILED = "GET_ALL_POLLS_FAILED";

// QUESTION ACTIONS
export const GET_ALL_QUESTIONS_STARTED = "GET_ALL_QUESTIONS_STARTED";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS";
export const GET_ALL_QUESTIONS_FAILED = "GET_ALL_QUESTIONS_FAILED";
export const REMOVE_QUESTION_OPTION = "REMOVE_QUESTION_OPTION";
export const ADD_QUESTION_OPTION = "ADD_QUESTION_OPTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const ADD_NEW_QUESTION = "ADD_NEW_QUESTION";


// ANSWER ACTIONS
export const SET_ANSWER = "SET_ANSWER";
export const SEND_POLL_ANSWERS_STARTED = "SEND_POLL_ANSWERS_STARTED";
export const SEND_POLL_ANSWERS_SUCCESS = "SEND_POLL_ANSWERS_SUCCESS";
export const SEND_POLL_ANSWERS_FAILED = "SEND_POLL_ANSWERS_FAILED";

// CREATE POLL ACTOPNS
export const CREATE_QUESTION = "CREATE_QUESTION";
export const DELETE_CREATED_QUESTION = "DELETE_CREATED_QUESTION";
export const SEND_POLL_STARTED = "SEND_POLL_STARTED";
export const SEND_POLL_FAILED = "SEND_POLL_FAILED";
export const SEND_POLL_SUCCESS = "SEND_POLL_SUCCESS";
export const DELETE_POLL = "DELETE_POLL";